jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: mvn package -Dmaven.test.skip=true
    - continue-on-error: true
      run: mkdir staging && cp target/releases/* staging
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
    - continue-on-error: true
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: ${{github.event.inputs.tag}}
        files: staging/*.zip
        prerelease: false
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: "\u652F\u6301es${{github.event.inputs.es-version}}\u7248\u672C\u7684\
          \u5206\u8BCD\u63D2\u4EF6"
name: release elastic ansj plugin
on:
  repository_dispatch:
    types: trigger-ga___release.yml
